"""Metro (DMA) config, loaded from metros.json (generated by gen_metros.py).

METROS: state key -> list of {key, name, geo, dma, city, lat, lon}
  geo  = Google Trends metro code (US-XX-###)
  city = biggest city in the market, used for the "fire near {city}" keyword
  lat/lon = that city's center, for the PostHog visitor-radius filter
"""
import json, os

with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "metros.json")) as f:
    METROS = json.load(f)["states"]

RADIUS_MI = 50

# the "States in Play" / "Review Health" demand terms (Google Trends via fetch_trends.py demand, and the matching
# Search Console searches via gsc_sync.py): national = None
DEMAND_TEMPLATES = ["{} fires", "{} wildfires", "{} fire map", "{} wildfire map"]

def demand_terms(state=None):
    name = "" if state is None else state.replace("_", " ").replace("-", " ")
    return [t.format(name).strip() for t in DEMAND_TEMPLATES]

STATE_ABBR = {
    "minnesota": "MN", "georgia": "GA", "colorado": "CO", "utah": "UT",
    "oregon": "OR", "michigan": "MI", "washington": "WA", "florida": "FL",
    "idaho": "ID", "montana": "MT", "arizona": "AZ", "california": "CA",
    "wyoming": "WY", "oklahoma": "OK", "nevada": "NV", "texas": "TX",
    "wisconsin": "WI", "nebraska": "NE", "new-mexico": "NM",
    "south-dakota": "SD", "arkansas": "AR",
}
